### ISSUE TITLE
Missing dev_2015 file

### ISSUE THREAD

**Issue by nikhil741** [napsternxg/TwitterNER#1]
![screenshot from 2018-06-22 02-20-17](https://user-images.githubusercontent.com/17572184/41744992-21923e86-75c3-11e8-9ca9-75a39e639aa1.png)
From where I can get **dev_2015** file?
Can u please provide the explanation how to use it i.e where to place **tweets(test-data)** and recognize only person, location, and organization as entities?

**Comment by napsternxg** [comment]
Hi @nikhil741 you can download the full WNUT data files from https://github.com/aritter/twitter_nlp/tree/master/data/annotated/wnut16/data and then use one of the scripts to create the cleaned up file. 

The data cleaning script is provided in https://github.com/napsternxg/TwitterNER/blob/master/Data%20preprocessing.ipynb
