### ISSUE TITLE
Codec can't decode byte

### ISSUE THREAD

**Issue by jagan-pyt** [napsternxg/TwitterNER#6]
When running TwitterNER on my system on python 3.9 I am getting below error , could someone suggest how to over this 'Charmap' codec can't decode byte 0×8d in position 5470 :character maps to <undefined>

I am using Jupyter notebook through Pycharm.

Please suggest a solution

**Comment by jagan-pyt** [comment]
Resolved , thank you

**Comment by usykaa** [comment]
Hi! Could you please enlighten me on the solution to this? Really desperate to fix this

**Comment by usykaa** [comment]
Solved 
replaced line 83 of features.py with the following
 for line in open(dictDir + "/" + d,encoding="utf-8"):

**Comment by napsternxg** [comment]
Thanks a lot for this discussion. 
Can you send a PR with this change and I can integrate it in the repo.

**Comment by jagan-pyt** [comment]
Dear All,

I am also facing issues with word2vec , due to migration of gensim few
features have changed such as size and iter to vector size and epochs .. I
changed them but I am getting a error which states Word2vec has no
attribute intersect_word2Vec ...

For fixing this I  have downgraded gensim to 3.8.3 if I do so Run_ner is
having a issues with collections package .

Please suggest a solution

**Comment by jagan-pyt** [comment]
Dear All ,

I am trying to use Twitter NER in my project using gensim 4.2 but facing
multiples issues is there any fixes or changes in twitterNER module ??
